"""attack_reference category: lookup_attack_technique -- a local, offline
lookup over a slim copy of MITRE's public Enterprise ATT&CK dataset
(data/attack_enterprise_slim.json, generated by data/build_attack_data.py).

This is exploit_agent's fallback when a finding's skill file is only a stub
(no hand-authored methodology yet): instead of guessing from nothing, it can
look up the relevant ATT&CK technique by ID or free-text keyword and reason
from the returned description. Deliberately not live/networked -- the data
is static and bundled, so there's no runtime third-party dependency.
"""

from __future__ import annotations

import json
import os

MAX_RESULTS = 5
DESCRIPTION_TRUNCATE_CHARS = 500

_DATA_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "data", "attack_enterprise_slim.json")


def _load_techniques() -> list[dict]:
    with open(_DATA_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


_TECHNIQUES = _load_techniques()


def _truncate(text: str) -> str:
    if len(text) <= DESCRIPTION_TRUNCATE_CHARS:
        return text
    return text[:DESCRIPTION_TRUNCATE_CHARS] + f"... [truncated, {len(text) - DESCRIPTION_TRUNCATE_CHARS} more chars]"


def run_lookup_attack_technique(query: str) -> dict:
    """The actual lookup, as a module-level function so it's testable
    without going through the MCP tool wrapper.
    """
    if not query or not query.strip():
        return {"error": "query must be a non-empty technique id (e.g. 'T1190') or keyword string"}

    q = query.strip()
    q_upper = q.upper()

    exact = [t for t in _TECHNIQUES if t["technique_id"] == q_upper]
    if exact:
        return {"query": query, "match_type": "exact_id", "results": exact}

    q_lower = q.lower()
    keyword_matches = [
        t for t in _TECHNIQUES if q_lower in t["name"].lower() or q_lower in t["description"].lower()
    ]
    results = [
        {**t, "description": _truncate(t["description"])} for t in keyword_matches[:MAX_RESULTS]
    ]

    if not results:
        return {"query": query, "match_type": "none", "results": [], "note": "No technique matched this id or keyword."}

    return {
        "query": query,
        "match_type": "keyword",
        "result_count": len(results),
        "truncated_to": MAX_RESULTS if len(keyword_matches) > MAX_RESULTS else None,
        "results": results,
    }


def register(mcp, scope, executor, timeouts: dict) -> None:
    def lookup_attack_technique(query: str) -> dict:
        """Look up MITRE ATT&CK technique(s) by ID (e.g. "T1190") or
        free-text keyword search across technique name/description. Returns
        technique id, name, tactic(s), description, and a reference URL.
        Use this when no vulnerability-specific methodology is available for
        the current finding, to ground your testing approach in a real
        technique instead of guessing.
        """
        return run_lookup_attack_technique(query)

    mcp.add_tool(lookup_attack_technique)
